### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by mikesigs** [Particular/ServicePulse#1015]
There is no favicon in the browser. Check out this screenshot from DevTools that shows the the index.html has a link to an ico file that doesn't exist.

![image](https://user-images.githubusercontent.com/811177/109548605-15844e80-7a8a-11eb-9b20-193254c0ea66.png)

*Technical information:*

- **ServicePulse version:** 1.27.1
- **ServiceControl version:** 4.13.2
- **Browser version:** Vivaldi 3.6.2165.36

**Comment by danielmarbach** [comment]
@mikesigs Thanks for pointing it out. We will be looking at this during the next maintenance release window.

**Comment by sergioc** [comment]
@mikesigs I just checked and the favicon file is actually present: https://github.com/Particular/ServicePulse/blob/master/src/ServicePulse.Host/app/img/ServicePulse.ico

Have a look and feel free to re-open the issue if you need.

**Comment by WojcikMike** [comment]
Just for the record, when trying this it seems that:
 - The favicon works on FireFox
 - It does not work on Chrome and Edge
 - It works on FireFox, Chrome, Edge if ServicePulse is hosted on IIS

A bit of search resulted in information that:
https://stackoverflow.com/questions/11221292/local-file-website-favicon-works-in-firefox-not-in-chrome-or-safari-why
it is by design. Meaning Chromium does not support loading local ico file. 

Searching a bit, there does not seem to be a good solution for it. So I am afraid for now we would have to live with this.
