### ISSUE TITLE
Paging in the Events view is broken

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServicePulse#1559]
### Describe the bug

In the Events view (under `https://<host>/a/#/events`) the last page of the results is incorrect. It shows data both from the last page and the second to last page. E.g. if the page size is 20 and the total count of items is 61 then the last page shows 21 items instead of just 1.

**Comment by saschanm** [comment]
Possibly related but with a slightly different presentation.

Since upgrading ServiceControl to v5 both the last 10 events on the dashboard and the events tab paging are showing in reverse order

Dashboard shows the first 10 events after upgrade (and within retention period - 14 days for us) rather than the most recent.
Have to go to last page in events tab to see most recent - and those seem to also include some earliest events from 14 days back.

This suggests maybe a combination of this bug and another (maybe best as a ServiceControl issue)

**Comment by mikeminutillo** [comment]
Fixed by #1665
