### ISSUE TITLE
ServicePulse monitoring tab lists enpoints in descending order

### ISSUE THREAD

**Issue by robbaman** [Particular/ServicePulse#1593]
#### Is your improvement related to a problem? Please describe.
The ServicePulse Monitoring-tab lists all endpoints by name. But for reasons beyond me (or anyone in my team really), the default (hard coded) sort order is to sort them by alphabet in **descending** order. This means any time the page is refreshed or opened, we always need to click the name to 'correct' the sort order.

#### Describe the suggested solution
Ehh.. just sort it by alphabet in ascending order :)
        
#### Describe alternatives you've considered
We host ServicePulse in IIS and thus we already have the sources. At this point we change the `monitoring.dist.js` file manually after every update, but it seems a bit weird that we need to.

### Additional Context

The line that causes the issue is the following. By removing the `-` before `'-name'` the sort order is more natural.

https://github.com/Particular/ServicePulse/blob/0635bb1cb2e707de7746e32ee5507e5e33a36127/src/ServicePulse.Host/angular/app/modules/monitoring/js/monitored_endpoints.controller.js#L24

I'm not sure if a PR for such changes is required, recommended or even desired, but the change seems small enough.

**Comment by dvdstelt** [comment]
Hi, thanks for reporting this.

I'm not sure why we chose to sort it like that. But we're currently actively migrating all pages to Vue, since we were still using an old version of Angular and wanted something else.
The plan is to release that somewhere around the end of the month, although I can't really promise anything. So even though it's a minor change, releasing it and doing all the work around it is not really worth it at this point. Also because I'm not sure exactly _why_ we sort it like this. Maybe there's a reason I'm not aware of.

Anyway, the team currently working on it is aware of your request and will take it into consideration, if they didn't fix it already.
