### ISSUE TITLE
When there is a problem getting the results from SC API, the user should be properly notified

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServicePulse#168]
When there is any issue with retrieving data from SC API, ServicePulse should display a message after appropriate timeout.
At the moment, the spinning wheel to retrieve data keeps on spinning.

--
Related desk case: https://nservicebus.desk.com/agent/case/8183

**Comment by WojcikMike** [comment]
I verified this bug in the newest version and there is a message about problems with communication to Service Control.

I checked the code and it seems that was fixed with a release of version [1.4] (https://github.com/Particular/ServicePulse/releases/tag/1.4.0)
And the issue that described it is: #191 

Because it is fixed I will close this issue.
