### ISSUE TITLE
Duplicate endpoints with Octopus Deploy and ServicePulse - can not get work around to work properly

### ISSUE THREAD

**Issue by bjartwolf** [Particular/ServicePulse#174]
I am running NServiceBus 4.6.3 with ServicePulse 1.1.1 and ServiceControl 1.5.0

Currently I am trying to get the client to upgrade to using ServicePulse, but I am having some issues regarding the duplicate endpoints as described in https://github.com/Particular/ServicePulse/issues/134

I have tried the "HostIdFixer.cs" workaround as described in http://docs.particular.net/servicepulse/troubleshooting#duplicate-endpoints-appear-in-servicepulse-after-re-deployment in multiple variations but no luck so far. I've attached a debugger locally and can confirm that I get the same hostId from the CreateGuid even if I move the install-files to a new directory, but the Guid that ends up showing in ServicePulse is always a new one. I am not sure how to actually se which Guid is set on the endpoint.

I've tried to read through the source, but I can't see any changes to the HostInformation class since 4.6.3 before 5.x, but maybe I'm wrong. 

This is the log from ServicePulse when I install the endpoint, where I always get a new GUID in the /host/GUID even if the GUID generated in HostIdFixer is the same (as mentioned I am checking this with attaching the debugger )

Endpoint '[MYENDPOINTNAME]' started at 24.02.2015 09:06:19 on host [MYMACHINENAME]
a minute ago info EndpointControl
/endpoint/[MYENDPOINTNAME]
/host/81f28cc7-b1a5-d0d0-bd3d-1ad1c005d365
Endpoint [MYENDPOINTNAME] running on host [MYMACHINENAME]has been confirmed to have heartbeats enabled
a minute ago info HeartbeatMonitoring
/endpoint/KONSULE-SG2EPLI
/host/81f28cc7-b1a5-d0d0-bd3d-1ad1c005d365
New '[MYENDPOINTNAME]' endpoint detected at '[MYMACHINENAME]'. In order for this endpoint to be monitored the plugin needs to be installed.
a minute ago info EndpointControl
/endpoint/[MYENDPOINTNAME]
/host/81f28cc7-b1a5-d0d0-bd3d-1ad1c005d365
Endpoint '[MYENDPOINTNAME]' started at 24.02.2015 09:06:07 on host [MYMACHINENAME]
a minute ago info EndpointControl
/endpoint/[MYENDPOINTNAME]
/host/81f28cc7-b1a5-d0d0-bd3d-1ad1c005d365

**Comment by SimonCropp** [comment]
@bjartwolf 

Firstly there was some duplication in the documentation. So http://docs.particular.net/servicepulse/troubleshooting#duplicate-endpoints-appear-in-servicepulse-after-re-deployment now points to http://docs.particular.net/nservicebus/override-hostid

Next the old approach in the doco that recommended using IWantToRunWhenBusStartsAndStops was flawed. It failed to consider a possible race condition caused by some downstream code that made use of the HostId inside another implementation of IWantToRunWhenBusStartsAndStops. Since the order of multiple IWantToRunWhenBusStartsAndStops is non-deterministic sometimes your HostId override would run after some usages of the default HostId.

So I have changed the doco to use the IWantToRunWhenConfigurationIsComplete and the host override code is then placed in the constructor http://docs.particular.net/nservicebus/override-hostid#how-do-i-override-an-endpoint-host-identifier

Can you please try this approach?

**Comment by bjartwolf** [comment]
:thumbsup: 
Worked locally when I installed, moved install files and re-installed. I'll try to roll out in staging environments later, but it should be fine to close the issue. Thanks!

**Comment by SimonCropp** [comment]
@bjartwolf good to hear. and sorry about the bad doco
