### ISSUE TITLE
When retrying a failed message there is no feedback of what is happening...

### ISSUE THREAD

**Issue by sfarmar** [Particular/ServicePulse#224]
In a call with a customer we noticed this misleading behavior:

If we navigate to the failed messages screen, select a message and retry, we get a blue banner at the top saying  `Retrying 1 messages...`, however if you navigate away for the page and get back to the failed messages screen, you have no feedback whatsoever...

I noticed that if we go to the dashboard after 30 seconds or so we get `1 failed message(s) submitted for retry`.

It may be a good idea to have that feedback on the failed messages screen as well, or some kind of durable feedback on the failed messages screen?

**Comment by petersgiles** [comment]
@mikeminutillo we could do this if SC gave me feedback about where the action was up to. I do these using a promise now and the api allows for progress updates. So instead of taking the request and giving me an ACK, it would ping me every few secs saying where it was at and then finally telling me that the retry was being attempted.

**Comment by petersgiles** [comment]
moved to platform dev https://github.com/Particular/PlatformDevelopment/issues/674
