### ISSUE TITLE
Access to http://platformupdate.particular.net/servicepulse.txt results in unsafe script warning accessed via SSL

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#231]

**Comment by petersgiles** [comment]
This is actually a config issue, in `app.constants.js` you can change the `service_pulse_url` to have `https://` instead of `http://`. I expect it would work with `//:` and no protocol. If that does work we could make that the default.

I expect this is the scenario where you extract it and host in your own browser. I don't have an environment setup with SSL wrapping SP. @ramonsmits could you try editing `app.constants.js` and see how you go.

**Comment by petersgiles** [comment]
While my instructions are technically correct we actually need to host the release notes in a place that accepts https requests.. @gbiellem is looking at what can be done.

**Comment by gbiellem** [comment]
Relates to https://github.com/Particular/Website.Frontend/issues/376

**Comment by petersgiles** [comment]
@gbiellem the code in SP already doesn't care about the protocol is there anything else this needs from a SP perspective?

**Comment by gbiellem** [comment]
> l is there anything else this needs from a SP perspective

No this is purely an infrastructure problem not an SP problem.

**Comment by petersgiles** [comment]
@gbiellem I'll leave this issue open until it's done anyway
