### ISSUE TITLE
Installer UI, long ServiceControl URI is not visible as you type

### ISSUE THREAD

**Issue by sfarmar** [Particular/ServicePulse#233]
If you paste or type a long address in ServiceControl Instance URI the text does not scroll (if that make sense?)
![sp](https://cloud.githubusercontent.com/assets/125256/11471866/311d7224-9760-11e5-8379-7b90a6d0eb86.PNG)

**Comment by gbiellem** [comment]
Gee thanks @petersgiles  :)

**Comment by gbiellem** [comment]
Did some investigation into this.  The problem stems from the chosen theme in Advanced Installer. Basically it's broken for all text boxes in that theme.   For ServiceControl we moved back to the classic theme to get around similar problems. 

@sergioc provided me with some assets for the SC installer update and I think he also produced some for SP because we though we would want to move to a consistent theme. 

Switching themes is a little bit more labor intensive than it sounds as it also dumps some of the dialog customizations, so basically we have to do some parts from scratch.  

@sergioc any idea where those SP assets are? (Seems I have goldfish memory)

**Comment by gbiellem** [comment]
@sergioc - never mind, I found them  - https://www.dropbox.com/sh/raukllxg2rleaw1/AAChEWzZDXhOjuyQyyTR_9qIa?dl=0
