### ISSUE TITLE
Feature request: Tag failed messages

### ISSUE THREAD

**Issue by christoffer-lundqvist** [Particular/ServicePulse#283]
A failed message is not always "transient" i.e DB is down, and a simple retry will fix the failure.

We need functionality to perhaps group failed messages by tags i.e 
Tag a message with "Needs code fix"
Tag a message with  "Data inconsistency error"
Tag a message with  "Contact business"
Tag a message with  "release version"

Our old "monitor" had the ability to put messages "on hold". With that function the board would still look "Green" even though there are failed messages on hold.

**Comment by WilliamBZA** [comment]
I think this is a FANTASTIC idea! Potentially also be able to do this at a group level so any new failures coming in for a group that needs code changes won't be flagged incorrectly.

**Comment by petersgiles** [comment]
relates to https://github.com/Particular/ServicePulse/issues/164

**Comment by Maqster6** [comment]
We need someway to collaborate around the failed messages/groups so that we can see if someone is working on the issue. 

Say that we have a failed message, that needs a bug-fix to be able to solve the message failure. 
Then it would be awesome if we could add an external link to the reported bug.
If there is a failure that needs a code fix, then it will take longer time then 15 min to solve it, so if we mark the case the dashboard still needs to be green or yellow, if there is a new failure then it will turn red again. 

I think this would be really helpful, as christoffer-lundqvist said we used to have this when we where rolling our own monitoring.

If you want to do this in a skateboard fashion, then just add a comment field on the failed message group and a comment field on each failed message. That would get it started and out the door. I think the message could be cleared on retry

**Comment by christoffer-lundqvist** [comment]
Bra. Har själv skickat in en issue på detta. De jobbar nog med det. 

Skickat från min iPhone

**Comment by christoffer-lundqvist** [comment]
I really need this issue to be fixed :)

**Comment by Maqster6** [comment]
How are we doing on this feature, I think this would help us tremendously?

**Comment by lailabougria** [comment]
Added in [ServicePulse 1.30.0](https://discuss.particular.net/t/servicepulse-1-30-minor-release-available/2443)
