### ISSUE TITLE
Failed Messages list - Need to click on the checkbox to select an item

### ISSUE THREAD

**Issue by Bishbulb** [Particular/ServicePulse#296]
This is a minor usability complaint. On the Failed Messages list, you need to click directly on the checkbox in order to select the message for the purpose of Retry/Archive.

This screen used to allow you to click anywhere on the row to select the message.

**Comment by sergioc** [comment]
@Bishbulb we restored the old behavior (click row to select) for the time being, but we'll again disable row click to select, since we're using row clicking to access screens/states everywhere else in SP. 

We'll keep the issue open until we find a good compromise for making the selection of messages easy without resorting to row clicking.

**Comment by sergioc** [comment]
@Bishbulb we've recently [released ServicePulse v1.8.0](https://github.com/Particular/ServicePulse/releases/tag/1.8.0), which contains some changes affecting this issue. 

v1.8.0 introduces a new dedicated message page to examine message data instead of showing that data inline in the messages lists.

In order to give access to individual message pages, you can click almost anywhere in the whole row from the message in the message list. This breaks the click row to select behavior we had so far. 

However, we still took into account the problem in this issue and created a generous checkbox hotspot area on the left side of each row to make selection easy.

Have a look and let us know what you think!
