### ISSUE TITLE
Ability to bookmark an error message or error grouping

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServicePulse#331]
When the DevOps team captures the information from ServicePulse, sometimes they will need to work with their dev team to indicate the problem. 
It will be nice if DevOps can go to a certain error message or error group and bookmark the Url and simply send the Url to the dev team. 
Currently the user experience is that based on the information from DevOps, the dev will have to go to SP and scroll down to the exact message group. A bookmark function would make this easier.

Requested by Customer

**Comment by petersgiles** [comment]
There is a copy to clipboard function, is that not adequate?

**Comment by sergioc** [comment]
@indualagarsamy if there is a support case, can you link here?

**Comment by kevin-whalley-gc** [comment]
Hi @petersgiles,

Are you referring to the 'Copy Id to clipboard'?

If a dev ops team member provides that I must launch SI (takes 30+ seconds), switch to the environment (5-30 seconds), paste it in and search (5-15 seconds)

Once SI is launched subsequent messages are easier, but in the intervening time period there is no context to the message.

I mentioned this request to @indualagarsamy because we have our DevOps team monitoring SP and triaging issues, at best they can break it down to Endpoint and Failed Message Group, but in order to look at a particular group, I need to launch SP, switch to failed messages (I have book marked this bit) and then do a Ctrl-F for the exception message they provided, which may or may not be on the first 'page' so I must scroll down, then click on 'View Messages', wait for it to load and then I can inspect the exception messages and message details

If the DevOps group where to provide ids for each message, they would have to copy each one (conservatively, once per failed message group) and copy the name of the message group.

The goal here would be to allow the dev team to receive a report (triaged) and then click on links to view the the message groups which interest them and drill down from there

**Comment by petersgiles** [comment]
@kevin-whalley-gc I think I understand what you're after, I do think this is a useful feature and I am pretty sure there's a 'no fuss' way to do this but it might take a bit of time to prioritize and get it done. 

---

In the meantime and because you need something today, you can query the ServiceControl api directly with the message id copied to the clipboard

The ServiceControl Api is available here `http://localhost:33333/api` (replace localhost with your URL, you may have problems with accessing port 33333 depending on your network security, get them to make a rule for your IP address if you have any issues)

You can query the messages with this url `http://localhost:33333/api/messages/search/{keyword}?[page,per_page,direction,sort]` for example `http://localhost:33333/api/messages/search/84de087e-e0b8-4ef3-a4aa-a5e100cd7883`

If you put that into your browser it will come back as json but it's not that pretty. I use a tool called [Postman ](https://www.getpostman.com/)to make the call which is just a good tool generally for querying web apis.

**Comment by kevin-whalley-gc** [comment]
@petersgiles, Thanks. It's not a practical solution so homefully this gets prioritized soon.

Another scenario: I need to direct our AppOps team to look at a set of messages by the name of the failed message group, I have to give them the name, they have to load up ServicePulse and find it. Most helpful if I could have just linked them

**Comment by WojcikMike** [comment]
It seems like one of the solutions to that would be to create a page displaying failed message. Let's say that we will have url: http://localhost:9091/app1/#/failedMessage/{here-comes-guid}

That would initially display the same information as on failed message list. In this case we can start adding links to the failed message if needed and send it around between dev-ops and dev team. 

Providing such page would allow us to provide better linking possibility in the application.

@Particular/servicepulse-maintainers what do you think?

**Comment by WilliamBZA** [comment]
I like the suggestion @WojcikMike

**Comment by sergioc** [comment]
:+1: it could tie in with https://github.com/Particular/ServicePulse/issues/308

**Comment by sergioc** [comment]
FYI this has been addressed in the v1.8.0 release.
