### ISSUE TITLE
IIS hosting only supports site root for ARR proxy

### ISSUE THREAD

**Issue by rlaveycal** [Particular/ServicePulse#343]
## Symptoms

ServicePulse does not receive updates from the ServiceControl

## Who is affected

Any user attempting to install ServicePulse using ARR proxy in a non-root directory.

## POA

- [x] Update ServicePulse SignalR version to latest stable. #345
- [x] Smoke Test ServiceControl / ServicePulse
- ~~[ ] Create new release of ServicePulse~~
- ~~[ ] Announcement~~

## User Report:
Following the instructions to install under IIS (http://docs.particular.net/servicepulse/install-servicepulse-in-iis) works so long as the `api` proxy folder to service control is in the site root. If it's not (e.g. to host multiple service pulse instances talking to multiple service control instances) then the SignalR connect and related calls don't respect the correct URL and continue to use `/api/messagestream'

E.g. with service pulse installed in a /ServicePulse folder IIS logs show
```
GET /servicepulse/api/messagestream/negotiate _=1462878929505&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=6425b0eb-624e-4787-a75d-cbe5b3696c9d&SERVER-STATUS=200 80 - ::1 Mozilla/5.0+(Windows+NT+6.3;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko http://localhost/servicepulse/ 200 0 0 0
GET /api/messagestream/connect transport=webSockets&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAApuf%2B71QcnkWoqd1F9VXo4QAAAAACAAAAAAAQZgAAAAEAACAAAAA2oYDR7QjczTdf3cpMDI2gDzSfz3RbU1L2btfR2FL3ngAAAAAOgAAAAAIAACAAAACCjaerwjgwdaN6v6MEYfRqMu179Zp2u6K6UmEkXHNN0jAAAAB2Ib%2FO8P%2BvydfnS32GLZnxcdDwnuXVpJck%2FQLByz%2BVqFhfH4ZAf8E0guI2AVpXPxlAAAAA1%2FQsBAMgmlEAXIEm%2FagjdaHNptHUMYjDwFCvxZqevqY%2B47i%2F%2F37JHlXigdKpga9rabYZZLJNBGjE7%2BlJ2Y7G3A%3D%3D&tid=5&X-ARR-CACHE-HIT=0&X-ARR-LOG-ID=2458b1cd-0f84-4d84-9beb-0d5878920ae0&SERVER-STATUS=101 80 - ::1 Mozilla/5.0+(Windows+NT+6.3;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 502 5 2 0

```

**Comment by WilliamBZA** [comment]
Hi @rlaveycal 

Can you please confirm what value you configured for the `service_control_url` parameter in `app.constants.js`?  This [needs to be configured](http://docs.particular.net/servicepulse/install-servicepulse-in-iis#advanced-configuration) to reflect the url that the application will be hosted in, so in your case would probably be `/servicepuls/api` or something similar.

**Comment by rlaveycal** [comment]
Yes, it's set as you can see from the IIS log output. `negotiate` is called on the correct URL but `connect` on the wrong one.

This could be a SignalR bug - Pulse is using a very old version (1.1.3).

**Comment by WilliamBZA** [comment]
For version `1.1.3` this value needs to be set in the `config.js` file.

If the value has been set in the `config.js` file and you're still seeing the incorrect behaviour, is it possible for you to upgrade to the latest version of ServiceControl and ServicePulse?

**Comment by rlaveycal** [comment]
I'm using the latest version of SC and SP. 1.1.3 refers to the version of **SignalR** being used by SP

**Comment by boblangley** [comment]
Added PR with SignalR update. Smoke tested against https://github.com/Particular/ServiceControl/pull/724

**Comment by WilliamBZA** [comment]
Closed by https://github.com/Particular/ServicePulse/pull/345

New release of Service Pulse and Service Control will be coming soon to address this.

**Comment by WilliamBZA** [comment]
Service Control version `1.16.0` and Service Pulse version `1.6.0` have been released.

@rlaveycal can you please update and see if your issue is resolved?

**Comment by rlaveycal** [comment]
There's a problem with the self-hosted pulse. The new signalr JS isn't being returned
```
URL	Protocol	Method	Result	Type	Received	Taken	Initiator	Wait‎‎	Start‎‎	Request‎‎	Response‎‎	Cache read‎‎	Gap‎‎
/lib/jQuery/jquery.signalR-2.2.0.min.js	HTTP	GET	404	application/javascript	160 B	< 1 ms	<script>	374	0	0	0	0	1453
```

**Comment by WojcikMike** [comment]
### Regarding jqeury signalr 404
This is a bug. File jquery.signalR-1.1.3.min.js change it's name to jquery.signalr-2.2.0.min.js (upper R became lower). And Nancy that is used for self hosting is apparently case sensitive. On IIS this is not the issue.

### Regarding SignalR issue with ARP proxy

Internal tests shown that the issue is still there. The problem is that when SignalR calls negotiate method it uses proper url (in this case: /servicepulse/api/messagestream/negotiate...) but than SignalR use url returned from the server to make connection. This is the issue in SignalR that was reported by few people:

* [SignalR doesn't work behind Reverse Proxy] (https://github.com/SignalR/SignalR/issues/3287)
* [How to change appRelativeUrl] (https://github.com/SignalR/SignalR/issues/3649)
* [Stack Overflow question](http://stackoverflow.com/questions/32783993/signalr-connectivity-issue-with-reverse-proxy-cross-domains) describing the same issue

The offending line in SignalR is here:
https://github.com/SignalR/SignalR/blob/fa864e866bea4737dbd888f993892694f2f6b1a6/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js#l687

#### Possible resolution
As the issue lies in 3rd party library there are limited options. In ServicePulse we can't do anything as SignalR don't allow to modify the appRelativeUrl. And on ServiceControl we don't know anything about reverse proxy. The good solution for now would be to investigate if this issue can be solved on the infrastructure level configuring IIS to rewrite bad url.

**Comment by rlaveycal** [comment]
Annoying!

Just to add that Pulse 1.6 seems to treat the `service_control_url` setting as relative to the current folder

If set it to `/fred/api` then IE makes the following call
```
URL	Protocol	Method	Result	Type	Received	Taken	Initiator	Wait‎‎	Start‎‎	Request‎‎	Response‎‎	Cache read‎‎	Gap‎‎
/ServicePulse/fred/api	HTTP	GET	404	text/html	4.95 KB	1.09 s	XMLHttpRequest	5656	47	1047	0	0	1813
```

Setting it to `/api` (or `api`) calls `/ServicePulse/api`. Makes life easier.

**Comment by WilliamBZA** [comment]
Case sensitive loading of resources is fixed by release `1.6.1`.

An [issue has been logged](https://github.com/Particular/ServiceControl/issues/725) in ServiceControl to try and fix the Reverse Proxy issue.

**Comment by rlaveycal** [comment]
Success!

The solution is to add an output rewrite rule to IIS/ARR that handles the response from `negotiate` and inserts the path. This is my full `api\web.config`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://localhost:33333/api/{R:1}" />
                </rule>
            </rules>
            <outboundRules>
                <rule name="Update Url property" preCondition="JSON" enabled="true" stopProcessing="true">
                    <match filterByTags="None" pattern="\&quot;Url\&quot;:\&quot;(.+?)\&quot;" />
                    <conditions>
                        <add input="{URL}" pattern="(.*)/api/" />
                    </conditions>
                    <action type="Rewrite" value="&quot;Url&quot;:&quot;{C:1}{R:1}&quot;" />
                </rule>
                <preConditions>
                    <preCondition name="JSON">
                        <add input="{URL}" pattern="/api/messagestream/negotiate" />
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="application/json" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
    </system.webServer>
</configuration>
```

**Comment by malkinservicebus** [comment]
Hi @rlaveycal 

We would like to send you a token of appreciation. Please forward your postal address to operations@particular.net so that we can send you a special gift.

**Comment by WojcikMike** [comment]
Awesome @rlaveycal Grats!,

I allowed myself to create a PR to our documentation to include this rule until the bug is fixed. I verified the rule on my environment and it works nicely. We created a question on (SignalR forum)[http://forums.asp.net/t/2095053.aspx?SignalR+and+reverse+proxy] to clarify if there is a way to make it work without this URL rewrite rule I will update this issue with more information when we have them
