### ISSUE TITLE
Error when entering /failedMessages page directly

### ISSUE THREAD

**Issue by johansuperstar** [Particular/ServicePulse#358]
The following error occurs and the page won't render properly when visiting url **/failedMessages** without having clicked the ALL FAILED MESSAGES link in the navigation. 

`angular.js:12416 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at new controller (http://secc3459:9090/js/views/failed_messages/controller.js:20:39)
    at invoke (http://secc3459:9090/lib/angular/angular.js:4473:17)
    at Object.instantiate (http://secc3459:9090/lib/angular/angular.js:4481:27)
    at http://secc3459:9090/lib/angular/angular.js:9108:28
    at link (http://secc3459:9090/lib/angular/angular-route.js:977:26)
    at invokeLinkFn (http://secc3459:9090/lib/angular/angular.js:8746:9)
    at nodeLinkFn (http://secc3459:9090/lib/angular/angular.js:8246:11)
    at compositeLinkFn (http://secc3459:9090/lib/angular/angular.js:7637:13)
    at publicLinkFn (http://secc3459:9090/lib/angular/angular.js:7512:30)
    at boundTranscludeFn (http://secc3459:9090/lib/angular/angular.js:7656:16) <div id="view" ng-view="" class="ng-scope" data-ng-animate="1">`

It's probably due to this line: https://github.com/Particular/ServicePulse/blob/9b2159b4e4de4f40326fc3b87c6d901ba67c066a/src/ServicePulse.Host/app/js/views/failed_messages/controller.js#L20

That line of code also seems to want to redirect to the **/failedGroups** page if the selectedExceptionGroup is incomplete. However, I would like to have the possibility to link directly to the **/failedMessages** page.

To reproduce: 
- Go to **/failedMessages** 
- Clear local storage
- Refresh page

**Comment by WilliamBZA** [comment]
Good catch, thanks @johansuperstar!

I've gone through the code path that gets us to that error. The data for this page is loaded by the `failed_groups` controller and is persisted in LocalStorage. The `failed_messages` view then expects that the data has been loaded and persisted already. Obviously this is not going to be the case when navigating directly to the Failed Messages page.

To fix this we need to do the following:
* [ ] Extract the error messages loading logic to a service that can be called by both the `failed_groups` controller as well as the `failed_messages` controller
* [ ] Refactor the controllers to use the new service instead of loading the data directly
* [ ] Wire the loading phase up to the loading indicators

I'll work on the changes and let you know once a release is ready for you to try.

**Comment by johansuperstar** [comment]
Thanks for picking this up :)

**Comment by WilliamBZA** [comment]
@johansuperstar We've just released Version 1.6.4 which should allow you to bookmark the failed messages page and navigate there without requiring to first go to the groups.

Would you please download it and see if it fixes your problem?

**Comment by johansuperstar** [comment]
Tested it, and it's working now :)

Thanks for fixing this!

**Comment by WilliamBZA** [comment]
Glad to hear it!
