### ISSUE TITLE
Archive grouped messages doesn't complete in one action

### ISSUE THREAD

**Issue by JSCProjects** [Particular/ServicePulse#424]
If I want to archive grouped messages(more than 100) ServicePulse askes me to archive this group. My expectation is that when I click yes it will complete this action in one click. Now I have to click it sometimes more than 20x times to archive several hundreds of messages.

***************

*Technical information if reporting bug:*

- **ServicePulse version: ServicePulse v1.8.2** 
- **ServiceControl version: ServiceControl v1.36.0**

**Comment by WojcikMike** [comment]
@JSCProjects thank you for raising this issue. I tried to reproduce it in my environment and I had slightly different results. After clicking archive the whole group was eventually archived yet the progress of that operation is not reported in any way. So I could see that archive count (in the tab) was updating but the group was displayed in a normal way. Every now and then it's message count would update but it is a very confusing process. 

We are planning to increase the amount of information that user receives while archiving a group to match the experience with retrying a group. I will let you know when we implement this feature so that you can try it out

**Comment by WojcikMike** [comment]
@JSCProjects today we released SP version 1.9.1 and SC version 1.39. Those versions include updated archive group experience. Which should inform you of the status of the operation. Please try it out and let me know if the issue still occur.

**Comment by JSCProjects** [comment]
@WojcikMike I've installed this version on our servers and it works really a lot better now. There was one situation that when I archived 6000 msgs from a specific endpoint and started to archive another group. The big archive action failed and now servicepulse mentions it duplicated the message count and it's impossible to archive it now.

**Comment by WilliamBZA** [comment]
@JSCProjects The RavenDB indexes should have updated by now, are the message counts still incorrect?

**Comment by JSCProjects** [comment]
Yup. See screenshot

[cid:image003.jpg@01D2AD48.7D99D5D0]

Met vriendelijke groeten / Kind regards,

Joey Chömpff

[http://www.jsc-projects.nl/userfiles/newlogo50percent.png]

JSC Projects
Blankena 16
8103 JC Raalte

Telefoon: 06-150 12 458
E-Mail: mail@jsc-projects.nl<mailto:mail@jsc-projects.nl>
Internet: http://www.jsc-projects.nl<http://www.jsc-projects.nl/>
Twitter: @JSCProjects<http://twitter.com/#!/jscprojects>
KvK te Zwolle: 08178187
BTW: NL105372055B01
Bankrekening: NL78 RABO 0110 2858 08

**Comment by WilliamBZA** [comment]
@JSCProjects It doesn't look like Github likes displaying inline attachments from email replies. Are you able to reply using the github ui?

**Comment by JSCProjects** [comment]
<img width="513" alt="capture" src="https://cloud.githubusercontent.com/assets/19533149/24655031/afbbd062-193c-11e7-8ed0-0d8fc3c8023f.PNG">
