### ISSUE TITLE
Message stays in pending retries state after being moved to the error queue again by a redirected endpoint

### ISSUE THREAD

**Issue by Niklas-Peter** [Particular/ServicePulse#425]
Describe your problem / suggestion / idea / feedback here.

1. Message failed in endpoint A
2. Configure redirect in ServicePulse from A to B
3. Retry the message
4. Message fails in B again with another exception
5. The retry message is listed in failed messages, but the original message is still in pending retries.

The endpoints use the same configuration. Auditing is enabled.

***************

*Technical information if reporting bug:*

- **ServicePulse version:** 1.7.0
- **ServiceControl version:** 1.33.0

**Comment by indualagarsamy** [comment]
@Niklas-Peter - Thanks for your feedback. We will try to see if we can reproduce this on our end. cc / @Particular/servicepulse-maintainers

**Comment by mikeminutillo** [comment]
I think I know why this happens. 

When a failed message is ingested by ServiceControl it is stored in the embedded database. If the record was already in the database it's status is updated (usually from Pending to Unresolved). In order to accommodate events, the unique identifier for each failed message is a combination of the Message Id (usually a GUID) and the Processing Endpoint. 

With a redirect, you are effectively changing the Processing Endpoint. When the message fails again, the resulting failed message is not matched back to the original one. 

The result is two failed message records. One for the original address and one for the new address. The original one remains pending because we haven't linked it back to the incoming failed message. The new one is listed as Unresolved with only a single processing attempt. 

cc @Particular/servicecontrol-maintainers

**Comment by SzymonPobiega** [comment]
@mikeminutillo seems like a bug in SC? We should store the original processing endpoint somewhere e.g. in a "ServiceControl.OriginalProcessingEndpoint" header that is attached when doing a redirected retry.

**Comment by mikeminutillo** [comment]
@Niklas-Peter we have just released [ServiceControl 1.41.0](https://github.com/Particular/ServiceControl/releases/tag/1.41.0) which should resolve this issue.
