### ISSUE TITLE
*Request retry* label text should be "Retry group"

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServicePulse#441]
The text *Request retry* is not clear. Probably better if it is labeled as *Retry group*

![image](https://cloud.githubusercontent.com/assets/152998/25383999/c7e3f1d2-29be-11e7-95de-90ca8f6dfea1.png)

SC Version: 1.9.1

**Comment by sergioc** [comment]
Reason summary: we adopted that label because there's no guarantee those messages will be retried. 

Clicking that link will initiate an operation that is concluded when the messages are queued up for processing. However, processing is also part of the retry "pipeline", so only after processing will messages be effectively retried. Processing itself is a separate operation and there's currently no indication of when will it happen or whether it'll succeed.
