### ISSUE TITLE
Configuration tab settings not respected in Monitoring tab - no way to disable monitoring an instance

### ISSUE THREAD

**Issue by CRuppert** [Particular/ServicePulse#588]
ServicePulse 1.11.0
ServiceControl 1.4.5 (with monitoring package installed as well)

Configuration to ignore endpoints does not affect monitoring notifications.

Steps to reproduce:
1. Spin up endpoint on new host (using default endpoint naming strategy endpoint@host)
2. Wait for it to be registered in ServiceControl/ServicePulse
3. Stop endpoint
4. Go to Configuration tab in ServicePulse
5. Disable new host
6. Go to Monitoring See big red exclamation points telling you that you are bad and wrong and should suffer.

**Comment by CRuppert** [comment]
I just want to point out that this is particularly annoying if you autoscale or anything remotely like that. Granted, that's an annoyance in general with SP, but that's expected to some extent with autoscaling and monitoring.  But at least we have the settings to disable monitoring on autoscale hosts for the rest.

**Comment by WilliamBZA** [comment]
Hi @CRuppert 

The Monitoring instances don't actually look at the Enabled/Disabled flag within ServicePulse. There are a few reasons for this:

1. Compiling and sending the metric information is not a cheap operation. It's efficient, but there is definitely an overhead. If an endpoint is sending this information but is disabled, the metrics plugin should rather be removed from the endpoint.
2. The monitoring endpoints could be completely different from the recoverability and auditing endpoints that ServiceControl normally manages.
3. We've changed how we deal with scaling (both auto and manual). This is the key point here so I'll discuss this in a bit more detail:

As you mentioned, if an endpoint instance is scaled down, there's a manual step involved in telling service pulse not to care about heartbeats or custom checks from that endpoint. This is an extremely limiting way of dealing with scaling, especially in high throughput scenarios where auto scaling happens often.

To deal with this, we changed the way we deal with logical endpoints and physical endpoint instances within Monitoring. It's not complete yet, but it's much better than having to fiddle with enabled/disabled toggles:

In instances where endpoints are expected to scale or change their Host IDs, we instruct users to specify an [Instance ID](https://docs.particular.net/nservicebus/operations/metrics/service-control#configuration-instance-id) for the endpoint. By specifying the instance Id, if that instance restarts on different hardware/path or the host ID changes for any reason, that instance still reports to the correct instance within the monitoring screen and you don't have to enable or disable the old instance yourself.

I mentioned that it's not yet complete. There are a couple improvements still missing. Firstly, if the instance ID is different between scaled out instances, we have no way of removing the scaled down instances automatically. This is only a problem if you do not specify the instance ID though.

**Comment by CRuppert** [comment]
This makes a lot of sense. Is the plan to extend the same behavior in ServiceControl/ServicePulse in general?

It's possible I'm being dumb and that already exists for normal heartbeats/etc? Right now we have the same identical problem with Azure Webapp endpoints, since instance ids seem to change on a frequent basis, when they get replaced by Azure we get things like this:

UnitA.WebApis@RD0003FFA98ACB
latest heartbeat received 9 hours ago

UnitB.WebApis@RD0003FFA9BD346
latest heartbeat received an hour ago

**Comment by WilliamBZA** [comment]
The plan is indeed to extend that concept to the rest of ServiceControl and ServicePulse. We're in the process now of planning a big update to ServiceControl to allow us to make it cloud-native, thereby directly supporting the scaling and fluid nature of cloud deployments. This will, of course, also extend to on-premise environments that scale occasionally.

The heartbeat behaviour you're describing is precisely a symptom of this.

At the moment the `InstanceId` that you specify is only used by the monitoring portion. If heartbeats are important to you though, the monitoring portion already includes an "up" check that doesn't require the heartbeat plugin to be installed. It has less features (no configurable time, and no events raised on state changes) but does show you when the endpoints aren't processing messages via the "big red exclamation points telling you that you are bad and wrong and should suffer" 😂 

If you absolutely require the heartbeats, you can [hardcode the host ID](https://docs.particular.net/nservicebus/hosting/override-hostid) so that when Azure changes the host ID it won't create a new machine registered under the heartbeats page.

**Comment by CRuppert** [comment]
We've lived with it this long, we can continue to live with it. Knowing you folks have plans to deal with it is plenty good enough for me. :)

**Comment by WilliamBZA** [comment]
Can I ping you once we have _very early_ alpha bits available?

**Comment by CRuppert** [comment]
Sure, I can run it against our staging env.

I don't think that will be a problem

**Comment by WilliamBZA** [comment]
Thanks, I'll add you to the list 👍
