### ISSUE TITLE
ServicePulse fails to start after upgrading to 1.24

### ISSUE THREAD

**Issue by davidsavagejr** [Particular/ServicePulse#823]
Upgraded to 1.24 and ServicePulse fails to start.  Initial problem appeared to be a permission issue.  Running manually via cmd prompt or as "Local System" was able to get it into a "running" state but then I was only able to get an HTTP 503 when hitting the app via the browser.

It's hosted on port 80 and was working find up to 1.23

***************

*Technical information if reporting a bug:*

- **ServicePulse version:** 1.24
- **ServiceControl version:** 4.5.3
- **Browser version:** Brave 1.2.43

**Comment by saschanm** [comment]
Same here....service fials to start after upgrade from 1.23 to 1.24.

Windows logs show:
`Application: ServicePulse.Host.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at ServicePulse.Host.Hosting.Host.OnStop()
   at ServicePulse.Host.Hosting.Host.Dispose(Boolean)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(System.ServiceProcess.ServiceBase[])
   at ServicePulse.Host.Commands.RunCommand.Execute(ServicePulse.Host.Hosting.HostArguments)
   at ServicePulse.Host.Commands.CommandRunner.Execute(ServicePulse.Host.Hosting.HostArguments)
   at ServicePulse.Host.Program.Main(System.String[])
`

**Comment by Dunge** [comment]
Same, upgraded for no reason other than the "new version available" link in the page, and now the service shut down after starting it.

**Comment by saschanm** [comment]
I got blue screen when I attempted to uninstall also. After restart I uninstalled manually and then reinstalled a clean install of 1.24. Same issue with null reference exception.

Uninstalled and reinstalled previous version 1.23 without issue.

**Comment by WojcikMike** [comment]
Hi @saschanm , @Dunge and @davidsavagejr 

Thank you for your posts. We are working on the fix of that issue.

**Comment by janovesk** [comment]
Hey, @saschanm , @Dunge and @davidsavagejr! 

Could you run `netsh http show urlacl` in a command window for me and see if you find any reservations for port 8081 (or whatever other port you have configured ServicePulse to run on)? If so, can you paste the value here? It should look something like :

**Comment by janovesk** [comment]
We [just released](https://discuss.particular.net/t/servicepulse-1-24-0-patch-release-available/1609) 1.24.1 to fix this issue.  Check it out and let us know if there are any other issues.

**Comment by janovesk** [comment]
For those interested, the problem was that NancyFX and OWIN treat listening to a localhost URL differently. NancyFX will, by default, listen to all hostnames if you tell it to listen to localhost while OWIN will not. This created a crash with the registered urlacl registration for OWIN. With this fix, the old behavior is back.

**Comment by davidsavagejr** [comment]
Up and running on 1.24.1, installed without any issues.
Awesome turnaround, thanks guys!

**Comment by saschanm** [comment]
Confirmed working for me too on 1.24.1.

Thanks for the quick fix.
